// auth
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const TOPICS_REQUEST = "TOPICS_REQUEST"
export const TOPICS_SUCCESS = "TOPICS_SUCCESS"
export const TOPICS_FAILURE = "TOPICS_FAILURE"
export const TOPICS_UPDATE_REQUEST = "TOPICS_ADD_REQUEST"
export const TOPICS_UPDATE_FAILURE = "TOPICS_ADD_FAILURE"
export const TOPICS_ADD_SUCCESS = "TOPICS_ADD_SUCCESS"
export const TOPICS_REMOVE_SUCCESS = "TOPICS_REMOVE_SUCCESS"