// auth
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const PUSH_SUCCESS = "PUSH_SUCCESS"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const TOPICS_LOAD_REQUEST = "TOPICS_LOAD_REQUEST"
export const TOPICS_LOAD_SUCCESS = "TOPICS_LOAD_SUCCESS"
export const TOPICS_LOAD_FAILURE = "TOPICS_LOAD_FAILURE"
export const TOPICS_UPDATE_REQUEST = "TOPICS_ADD_REQUEST"
export const TOPICS_UPDATE_FAILURE = "TOPICS_ADD_FAILURE"
export const TOPICS_ADD_SUCCESS = "TOPICS_ADD_SUCCESS"
export const TOPICS_REMOVE_SUCCESS = "TOPICS_REMOVE_SUCCESS"
export const TOPICS_UPDATE_SUCCESS = "TOPICS_UPDATE_SUCCESS"
export const TOPICS_SELECT_TOPIC = "TOPICS_SELECT_TOPIC"

export const ORGS_LOAD_REQUEST = "ORGS_LOAD_REQUEST"
export const ORGS_LOAD_SUCCESS = "ORGS_LOAD_SUCCESS"
export const ORGS_LOAD_FAILURE = "ORGS_LOAD_FAILURE"

export const PREFS_SET_ORG = "PREFS_SET_ORG"

export const MEMBERS_LOAD_REQUEST = "MEMBERS_LOAD_REQUEST"
export const MEMBERS_LOAD_SUCCESS = "MEMBERS_LOAD_SUCCESS"
export const MEMBERS_LOAD_FAILURE = "MEMBERS_LOAD_FAILURE"

export const MESSAGING_STARTED = "MESSAGING_STARTED"
export const MESSAGING_STOPPED = "MESSAGING_STOPPED"
export const MESSAGING_ROOM_LOAD_SUCCESS = "MESSAGING_ROOM_LOAD_SUCCESS"
export const MESSAGING_MEMBERS_LOAD_SUCCESS = "MESSAGING_MEMBERS_LOAD_SUCCESS"
export const MESSAGING_MESSAGE_LOAD_SUCCESS = "MESSAGING_MESSAGE_LOAD_SUCCESS"
export const MESSAGING_MESSAGE_UPDATE_SUCCESS = "MESSAGING_MESSAGE_UPDATE_SUCCESS"
export const MESSAGING_FAILURE = "MESSAGING_FAILURE"
