# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new ios version to HockeyApp"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/topek.xcodeproj")
    cert
    sigh(adhoc: true)
    gym(scheme: "topek",
      clean: true,
      project: "./ios/topek.xcodeproj",
      configuration: "ReleaseAdhoc")
    hockey(api_token: "59e931660b6041908f0a6d160282439d")
    slack(message: "Successfully deployed new ios beta app to HockeyApp.")
  end

  desc "Deploy a new ios version to the App Store"
  lane :store do
    increment_build_number(xcodeproj: "./ios/topek.xcodeproj")
    #snapshot
    cert
    sigh
    gym(scheme: "topek",
      clean: true,
      project: "./ios/topek.xcodeproj",
      configuration: "Release")
    deliver(force: true)
    # frameit
  end

  after_all do |lane|

  end

  error do |lane, exception|
    slack(message: exception.message, success: false)
  end
end

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new android version to HockeyApp"
  lane :beta do
    # https://gist.github.com/boshajones/b7088262cfdd33470381d0c24ff2097c
    increment_android_version_code(path: "./android/version.properties")
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
    hockey(api_token: "59e931660b6041908f0a6d160282439d")
    slack(message: "Successfully deployed new android beta app to HockeyApp.")
  end

  desc "Deploy a new android version to the Play Store"
  lane :store do
    #gradle(task: 'clean', project_dir: "android/") # Clean the Gradle project
    #gradle(task: "assemble", build_type: "Release", project_dir: "android/") # Build the Release APK
    #supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end
  
  after_all do |lane|

  end

  error do |lane, exception|
    slack(message: exception.message, success: false)
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
